dist: xenial
language: python
jobs:
  include:
    - name:
      python: 3.9
      before_install: pip install pipenv
      install:
        - pipenv install --dev --skip-lock
        - echo "Using black to check Python code"
        - black --check *.py
      script: pytest tests/
