dist: xenial
language: python
jobs:
  include:
    - name:
      python: 3.9
      before_install: pip install pipenv
      install:
        - pipenv install --dev --skip-lock
        - echo "Using black, flake8, and pylint to check Python code"
        - black --check *.py
        - flake8 .
        - pylint geospatial/*.py --errors-only
      script: pytest tests/
