name: geospatial
channels:
  - conda-forge
  - esri
dependencies:
  - python=3.9
  - arcgis
  - gdal
  - imageio
  - matplotlib
  - scikit-image
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - jupyter
  - jupterlab
  - pip:
    - area
    - bokeh
    - cython
    - geojsonio
    - geopandas
    - geoplot
    - geopy
    - h5py
    - plotly
    - pygdal
    - pygis
    - pysal
    - vaex
    - dask
    - distributed
    - intake
    - intake-xarray
    - ipyleaflet
    - cartopy
    - keplergl
    - rasterio
    - rasterstats
    - requests
    - rtree
    - seaborn
    - xarray
    - basemap
    - hvplot
    - descartes
    - mapclassify
    - pygeoprocessing
    - geoviews